# frst ci 

image: alpine

before_script:
  - 'which ssh-agent || ( apk update && apk upgrade && apk add openssh-client git rsync )'
  - eval $(ssh-agent -s)
  # set up this variable in your account
  #- echo "$SSH_PRIVATE_KEY"
  #- echo "$SSH_PRIVATE_KEY" | ssh-add -
  - echo "$SSH_PRIVATE_KEY" | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  - ssh-keyscan ssh-gallem.alwaysdata.net >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  #- git config --global user.email "deployer@gallem.com"
  #- git config --global user.name "Deployer"


Deploy:
  script:
    - git clone https://gitlab.com/gallem/python-api-boilerplate.git pythonapi
    - scp -rvf pythonapi gallem@ssh-gallem.alwaysdata.net:/home/gallem/www
    # - rsync -rlvPz -F pythonapi/ gallem@ssh-gallem.alwaysdata.net:/home/gallem/www/
    # - ssh deployer@web4.woralelandia.com sudo systemctl restart nginx.service

