# frst ci
# i want to run a deploy to my server using a vps considering my most common access (ssh)
# how i configure:
# generate a ssh key on the server (ej: ssh-keygen -> use defaults and no password)
# ensure use the same domain -> ssh-copy-id -i $HOME/.ssh/id_rsa.pub [user]@ssh-[account].alwaysdata.net
# copy private key and public key to gitlab variables

image: alpine

before_script:
  - 'which ssh-agent || ( apk update && apk upgrade && apk add openssh-client git rsync )'
  - eval $(ssh-agent -s)
  # set up this variable in your account
  #- echo "$SSH_PRIVATE_KEY"
  #- echo "$SSH_PRIVATE_KEY" | ssh-add -
  - echo "$SSH_PRIVATE_KEY" | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  - ssh-keyscan ssh-gallem.alwaysdata.net >> ~/.ssh/known_hosts
  - echo "$SSH_PUBLIC_KEY" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  #- git config --global user.email "deployer@gallem.com"
  #- git config --global user.name "Deployer"


Deploy:
  script:
    - git clone https://gitlab.com/gallem/python-api-boilerplate.git pythonapi
    - scp -r pythonapi gallem@ssh-gallem.alwaysdata.net:/home/gallem/www
    # - rsync -rlvPz -F pythonapi/ gallem@ssh-gallem.alwaysdata.net:/home/gallem/www/
    # - ssh deployer@web4.woralelandia.com sudo systemctl restart nginx.service

